### ISSUE TITLE
Update PIPE_T_RXP to only accommodate the translation filter

### ISSUE THREAD

**Issue by chrisberthe** [Shopify/theme-lint#31]
The current regex for [`PIPE_T_RXP`](https://github.com/Shopify/theme-lint/blob/master/linters/i18n.js#L11) is currently not explicit enough to target only translation keys in Liquid. There are potentially other instances where `| t` will be referenced in Liquid but aren't necessarily related to actual translations.

For example: `{{ 'now' | time_tag: format: 'date' }}` will be targeted by the linter, and therefore throw an error:

![image](https://user-images.githubusercontent.com/991693/72386498-7e2a3380-36ef-11ea-9aec-568e149cd4d7.png)

cc @davidcornu

**Comment by davidcornu** [comment]
I see what you mean

```js
/\{\{\s*('|")((?:(?!\1).)+)\1\s*\|\s*t(?:ranslate)?(?::(.*?)\s*(?:\||\}\}))?/g
//                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
```

This capture group is optional which means we effectively allow anything after `| t`. Will see what I can do.
